version: '3'

services:
  queue:
    build:
      context: ./Docker/php
    volumes:
      - ./:/app
    restart: "always"
    networks:
      - default
    command: "php /app/bin/console messenger:consume async -vv --memory-limit=120M"
    depends_on:
      - redis

  redis:
    image: redis
    volumes:
      - redis_data:/data
    restart: "always"

volumes:
  redis_data: