version: '3'

services:

  fba-check-orders:
    build:
      context: ./Docker/php
    volumes:
      - ./:/app
    command: "php /app/bin/console domains:watch"
    depends_on:
      - queue

  queue:
    build:
      context: ./Docker/php
    volumes:
      - ./:/app
    restart: "always"
    networks:
      - default
    command: "php /app/bin/console messenger:consume async -vv --limit=5"
    depends_on:
      - redis

  redis:
    image: redis
    volumes:
      - redis_data:/data
    restart: "always"

volumes:
  redis_data: